# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cbind <- function(A, B) {
    .Call(`_TallerRcpp_rcpp_cbind`, A, B)
}

rcpp_maxmin <- function(A, B) {
    .Call(`_TallerRcpp_rcpp_maxmin`, A, B)
}

rcpp_multimatrix <- function(A, B) {
    invisible(.Call(`_TallerRcpp_rcpp_multimatrix`, A, B))
}

rcpp_rbind <- function(A, B) {
    .Call(`_TallerRcpp_rcpp_rbind`, A, B)
}

rcpp_whichmax <- function(A) {
    .Call(`_TallerRcpp_rcpp_whichmax`, A)
}

rcpp_whichmin <- function(A) {
    .Call(`_TallerRcpp_rcpp_whichmin`, A)
}

